import { config } from "dotenv";

config({path : `.env.${process.env.NODE_ENV || 'development'}.local`});

export const {
    PORT, NODE_ENV, DB_URI, JWT_SECRET, JWT_EXPIRES_IN, JWT_REFRESH_SECRET, JWT_REFRESH_EXPIRES_IN, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET, DEFAULT_DP, APP_PASS, USER_MAIL, CLIENT_URL, REDIS_HOST, REDIS_PORT, REDIS_PASSWORD, REDIS_TLS
} = process.env;